const orb=document.getElementById('orb'),panel=document.getElementById('panel'),status=document.getElementById('status'),messages=document.getElementById('messages'),input=document.getElementById('input'),send=document.getElementById('send'),talk=document.getElementById('talk'),close=document.getElementById('close');
let history=[],wakeRecognition=null,wakeEnabled=false,isAsking=false;
function setStatus(x){status.textContent=x}
function add(text,cls='j'){const d=document.createElement('div');d.className='msg '+cls;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function pickVoice(){const voices=speechSynthesis.getVoices();return voices.find(v=>/Daniel|Alex|Aaron|Google UK English Male|Microsoft.*Male/i.test(v.name))||voices.find(v=>v.lang==='en-US')||voices[0]}
function speak(text){if(!('speechSynthesis' in window))return;setStatus('SPEAKING…');if(wakeRecognition)try{wakeRecognition.stop()}catch{};speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.94;u.pitch=.82;u.voice=pickVoice();u.onend=()=>{setStatus(wakeEnabled?'LISTENING FOR “JARVIS”…':'READY • TYPE OR TALK');if(wakeEnabled)setTimeout(startWakeListening,350)};speechSynthesis.speak(u)}
async function ask(text){text=(text||'').trim();if(!text||isAsking)return;isAsking=true;add(text,'u');setStatus('THINKING…');send.disabled=true;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:history.slice(-8)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');history.push({role:'user',content:text},{role:'assistant',content:d.reply});add(d.reply);speak(d.reply)}catch(e){add('JARVIS error: '+e.message);setStatus(wakeEnabled?'LISTENING FOR “JARVIS”…':'READY • TYPE OR TALK');if(wakeEnabled)setTimeout(startWakeListening,500)}finally{send.disabled=false;isAsking=false}}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
function startWakeListening(){if(!wakeEnabled||!SR||isAsking||speechSynthesis.speaking)return;if(wakeRecognition)try{wakeRecognition.stop()}catch{};const r=new SR();wakeRecognition=r;r.lang='en-US';r.continuous=true;r.interimResults=false;r.onstart=()=>setStatus('LISTENING FOR “JARVIS”…');r.onresult=e=>{const said=Array.from(e.results).slice(e.resultIndex).map(x=>x[0].transcript).join(' ').trim();const m=said.match(/\bjarvis\b[\s,.:;-]*(.*)$/i);if(!m)return;panel.classList.add('open');const command=(m[1]||'').trim();try{r.stop()}catch{};if(command){ask(command)}else{speak('Yes?')}};r.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){wakeEnabled=false;talk.textContent='🎙️ Enable Wake Word';add('Microphone permission is needed for “JARVIS” wake listening.');setStatus('READY • TYPE OR TALK')}};r.onend=()=>{if(wakeEnabled&&!isAsking&&!speechSynthesis.speaking)setTimeout(startWakeListening,450)};try{r.start()}catch{}}
function enableWake(){if(!SR){add('Wake-name listening is not supported by this browser. Try Chrome or Safari with speech recognition enabled.');return}wakeEnabled=!wakeEnabled;talk.textContent=wakeEnabled?'🟢 “JARVIS” Listening':'🎙️ Enable Wake Word';if(wakeEnabled){add('Wake listening enabled. Say “JARVIS” for a response, or “JARVIS” followed by your request.');startWakeListening()}else{if(wakeRecognition)try{wakeRecognition.stop()}catch{};setStatus('READY • TYPE OR TALK')}}
orb.onclick=()=>{panel.classList.add('open');input.focus()};close.onclick=()=>panel.classList.remove('open');send.onclick=()=>{const t=input.value.trim();input.value='';ask(t)};input.onkeydown=e=>{if(e.key==='Enter')send.click()};talk.onclick=enableWake;
if('speechSynthesis'in window){speechSynthesis.getVoices();speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}
