const stage=document.getElementById('stage'),status=document.getElementById('status'),responseEl=document.getElementById('response'),hint=document.getElementById('hint');
let history=[],wakeRecognition=null,wakeEnabled=true,isAsking=false,isSpeaking=false,activated=false,persistentAudio=null,followUpMode=false,followUpTimer=null;
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
function setStatus(text,state=''){if(status)status.textContent=text;stage.classList.remove('listening','thinking','speaking');if(state)stage.classList.add(state)}
function showResponse(text=''){if(responseEl)responseEl.textContent=text}
function splitSpeech(text){const out=[];let rest=(text||'').replace(/\s+/g,' ').trim();while(rest.length){if(rest.length<=170){out.push(rest);break}let cut=Math.max(rest.lastIndexOf('. ',170),rest.lastIndexOf('? ',170),rest.lastIndexOf('! ',170),rest.lastIndexOf(', ',170),rest.lastIndexOf(' ',170));if(cut<70)cut=170;out.push(rest.slice(0,cut+1).trim());rest=rest.slice(cut+1).trim()}return out}
async function unlockAudio(){if(!persistentAudio){persistentAudio=document.createElement('audio');persistentAudio.setAttribute('playsinline','');persistentAudio.preload='auto';persistentAudio.style.display='none';document.body.appendChild(persistentAudio)}try{persistentAudio.muted=true;const silent='data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=';persistentAudio.src=silent;await persistentAudio.play();persistentAudio.pause();persistentAudio.currentTime=0;persistentAudio.muted=false;return true}catch(e){persistentAudio.muted=false;console.warn('Audio unlock failed',e);return false}}
async function playVoiceChunk(text){const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!r.ok){let e={};try{e=await r.json()}catch{};throw new Error(e.error||'Voice generation failed')}const blob=await r.blob(),url=URL.createObjectURL(blob);try{if(!persistentAudio)await unlockAudio();persistentAudio.pause();persistentAudio.src=url;persistentAudio.load();await new Promise((resolve,reject)=>{persistentAudio.onended=resolve;persistentAudio.onerror=()=>reject(new Error('Audio playback failed'));const p=persistentAudio.play();if(p)p.catch(reject)})}finally{URL.revokeObjectURL(url)}}
function stopRecognition(){if(wakeRecognition){try{wakeRecognition.onend=null;wakeRecognition.stop()}catch{}wakeRecognition=null}}
function scheduleListen(delay=350,followUp=true){clearTimeout(followUpTimer);followUpMode=followUp;followUpTimer=setTimeout(startListening,delay)}
async function speak(text,{continueConversation=true}={}){if(!text)return;isSpeaking=true;stopRecognition();setStatus('SPEAKING…','speaking');showResponse(text);try{for(const part of splitSpeech(text))await playVoiceChunk(part)}catch(e){console.warn('Dedicated voice failed',e);if('speechSynthesis'in window){await new Promise(resolve=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.9;u.pitch=.78;u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u)})}}finally{isSpeaking=false;scheduleListen(300,continueConversation)}}
async function ask(text){text=(text||'').trim();if(!text||isAsking)return;isAsking=true;stopRecognition();setStatus('THINKING…','thinking');showResponse(text);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:history.slice(-12)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');history.push({role:'user',content:text},{role:'assistant',content:d.reply});await speak(d.reply,{continueConversation:true})}catch(e){console.warn('ALFRED chat error',e);await speak('I had trouble reaching my brain. Please try that again.',{continueConversation:true})}finally{isAsking=false}}
function startListening(){if(!wakeEnabled||!activated||!SR||isAsking||isSpeaking)return;stopRecognition();const r=new SR();wakeRecognition=r;r.lang='en-US';r.continuous=false;r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>setStatus(followUpMode?'LISTENING…':'LISTENING FOR “ALFRED”…','listening');r.onresult=e=>{const said=Array.from(e.results).slice(e.resultIndex).map(x=>x[0].transcript).join(' ').trim();if(!said)return scheduleListen(250,false);stopRecognition();if(followUpMode){followUpMode=false;ask(said);return}const m=said.match(/\balfred\b[\s,.:;-]*(.*)$/i);if(!m){scheduleListen(250,false);return}const command=(m[1]||'').trim();if(command)ask(command);else speak('At your service.',{continueConversation:true})};r.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){activated=false;if(hint)hint.style.display='block';setStatus('TAP ONCE TO ALLOW MICROPHONE');return}if(e.error==='no-speech'){scheduleListen(250,false);return}console.warn('Speech recognition error',e.error);scheduleListen(500,false)};r.onend=()=>{if(wakeRecognition===r)wakeRecognition=null;if(wakeEnabled&&activated&&!isAsking&&!isSpeaking&&!followUpTimer)scheduleListen(350,followUpMode)};try{r.start()}catch{scheduleListen(500,false)}}
async function activate(){if(activated)return;if(!SR){setStatus('WAKE WORD NOT SUPPORTED IN THIS BROWSER');return}activated=true;if(hint)hint.style.display='none';try{await unlockAudio();const s=await navigator.mediaDevices?.getUserMedia?.({audio:true});if(s)s.getTracks().forEach(t=>t.stop())}catch{activated=false;if(hint)hint.style.display='block';setStatus('MICROPHONE / AUDIO PERMISSION NEEDED');return}await speak('ALFRED online. At your service.',{continueConversation:true})}
document.addEventListener('pointerdown',activate,{once:true});window.addEventListener('load',()=>setStatus('TAP ANYWHERE ONCE TO ACTIVATE ALFRED'));document.addEventListener('visibilitychange',()=>{if(document.hidden){stopRecognition();clearTimeout(followUpTimer);followUpTimer=null}else if(activated)scheduleListen(400,false)});
