const stage=document.getElementById('stage'),status=document.getElementById('status'),responseEl=document.getElementById('response'),hint=document.getElementById('hint');
let history=[],wakeEnabled=true,isAsking=false,isSpeaking=false,activated=false,persistentAudio=null,stream=null,recorder=null,followUpMode=false,followUpUntil=0,recordTimer=null,processingAudio=false;
function setStatus(text,state=''){if(status)status.textContent=text;stage.classList.remove('listening','thinking','speaking');if(state)stage.classList.add(state)}
function showResponse(text=''){if(responseEl)responseEl.textContent=text}
function splitSpeech(text){const out=[];let rest=(text||'').replace(/\s+/g,' ').trim();while(rest.length){if(rest.length<=170){out.push(rest);break}let cut=Math.max(rest.lastIndexOf('. ',170),rest.lastIndexOf('? ',170),rest.lastIndexOf('! ',170),rest.lastIndexOf(', ',170),rest.lastIndexOf(' ',170));if(cut<70)cut=170;out.push(rest.slice(0,cut+1).trim());rest=rest.slice(cut+1).trim()}return out}
async function unlockAudio(){if(!persistentAudio){persistentAudio=document.createElement('audio');persistentAudio.setAttribute('playsinline','');persistentAudio.preload='auto';persistentAudio.style.display='none';document.body.appendChild(persistentAudio)}try{persistentAudio.muted=true;const silent='data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=';persistentAudio.src=silent;await persistentAudio.play();persistentAudio.pause();persistentAudio.currentTime=0;persistentAudio.muted=false;return true}catch(e){persistentAudio.muted=false;console.warn('Audio unlock failed',e);return false}}
async function playVoiceChunk(text){const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!r.ok){let e={};try{e=await r.json()}catch{};throw new Error(e.error||'Voice generation failed')}const blob=await r.blob(),url=URL.createObjectURL(blob);try{if(!persistentAudio)await unlockAudio();persistentAudio.pause();persistentAudio.src=url;persistentAudio.load();await new Promise((resolve,reject)=>{persistentAudio.onended=resolve;persistentAudio.onerror=()=>reject(new Error('Audio playback failed'));const p=persistentAudio.play();if(p)p.catch(reject)})}finally{URL.revokeObjectURL(url)}}
function stopRecording(){clearTimeout(recordTimer);recordTimer=null;if(recorder&&recorder.state!=='inactive'){try{recorder.stop()}catch{}}recorder=null}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onloadend=()=>resolve(String(reader.result||'').split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(blob)})}
async function transcribe(blob){const audio=await blobToBase64(blob);const r=await fetch('/api/stt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio,mime:blob.type||'audio/webm'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Transcription failed');return (d.text||'').trim()}
async function handleTranscript(said){said=(said||'').trim();if(!said)return;if(Date.now()<followUpUntil||followUpMode){followUpMode=false;followUpUntil=0;await ask(said);return}const m=said.match(/\balfred\b[\s,.:;-]*(.*)$/i);if(!m)return;const command=(m[1]||'').trim();if(command)await ask(command);else await speak('At your service.',{continueConversation:true})}
function startAudioLoop(delay=200){if(!activated||!stream||isAsking||isSpeaking||processingAudio)return;clearTimeout(recordTimer);recordTimer=setTimeout(()=>{if(!activated||isAsking||isSpeaking||processingAudio)return;const chunks=[];let mr;try{mr=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':''})}catch{mr=new MediaRecorder(stream)}recorder=mr;mr.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};mr.onstop=async()=>{recorder=null;if(!chunks.length){startAudioLoop(150);return}processingAudio=true;try{const blob=new Blob(chunks,{type:chunks[0]?.type||mr.mimeType||'audio/webm'});const said=await transcribe(blob);await handleTranscript(said)}catch(e){console.warn('ALFRED STT error',e)}finally{processingAudio=false;if(activated&&!isAsking&&!isSpeaking)startAudioLoop(120)}};mr.start();setStatus(Date.now()<followUpUntil?'LISTENING…':'LISTENING FOR “ALFRED”…','listening');setTimeout(()=>{if(mr.state!=='inactive')mr.stop()},4200)},delay)}
async function speak(text,{continueConversation=true}={}){if(!text)return;isSpeaking=true;stopRecording();setStatus('SPEAKING…','speaking');showResponse(text);try{for(const part of splitSpeech(text))await playVoiceChunk(part)}catch(e){console.warn('Dedicated voice failed',e);if('speechSynthesis'in window){await new Promise(resolve=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.9;u.pitch=.78;u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u)})}}finally{isSpeaking=false;if(continueConversation){followUpMode=true;followUpUntil=Date.now()+9000}else{followUpMode=false;followUpUntil=0}startAudioLoop(250)}}
async function ask(text){text=(text||'').trim();if(!text||isAsking)return;isAsking=true;stopRecording();setStatus('THINKING…','thinking');showResponse(text);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:history.slice(-12)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');history.push({role:'user',content:text},{role:'assistant',content:d.reply});await speak(d.reply,{continueConversation:true})}catch(e){console.warn('ALFRED chat error',e);await speak('I had trouble reaching my brain. Please try that again.',{continueConversation:true})}finally{isAsking=false}}
async function activate(){if(activated)return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setStatus('VOICE CAPTURE NOT SUPPORTED IN THIS BROWSER');return}if(hint)hint.style.display='none';try{await unlockAudio();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});activated=true}catch{activated=false;if(hint)hint.style.display='block';setStatus('MICROPHONE / AUDIO PERMISSION NEEDED');return}await speak('ALFRED online. At your service.',{continueConversation:true})}
document.addEventListener('pointerdown',activate,{once:true});window.addEventListener('load',()=>setStatus('TAP ANYWHERE ONCE TO ACTIVATE ALFRED'));document.addEventListener('visibilitychange',()=>{if(document.hidden){stopRecording()}else if(activated&&!isAsking&&!isSpeaking)startAudioLoop(300)});
