(()=>{
const body=document.getElementById('tabletBody');if(!body)return;
const AXIOM='https://axiom.trade',KEY='j_axiom_paper_v3';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>Number(x)||0,fmt=x=>Number(x||0).toLocaleString(undefined,{maximumFractionDigits:8}),usd=x=>'$'+Number(x||0).toLocaleString(undefined,{maximumFractionDigits:2});
const cfg={feePct:.5,slipPct:1,maxPosPct:5,maxOpen:5,dailyLossPct:3};
function defaults(){return{active:'rookie',accounts:[{id:'rookie',name:'Rookie Sim',start:1000,balance:1000},{id:'scout',name:'Scout Sim',start:5000,balance:5000},{id:'pro',name:'Pro Sim',start:25000,balance:25000}],trades:[]}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');return d&&d.accounts?d:defaults()}catch{return defaults()}}function save(v){localStorage.setItem(KEY,JSON.stringify(v))}function acct(s){return s.accounts.find(a=>a.id===s.active)||s.accounts[0]}
function openUrl(u){window.JSafety?.log?.('axiom-open',u);window.open(u,'_blank','noopener,noreferrer')}
function todayPnl(s,a){const d=new Date().toDateString();return s.trades.filter(t=>t.accountId===a.id&&t.status==='closed'&&new Date(t.closedAt).toDateString()===d).reduce((z,t)=>z+n(t.pnlUsd),0)}
function openTrades(s,a){return s.trades.filter(t=>t.accountId===a.id&&t.status==='open')}
function equity(s,a){return a.balance+openTrades(s,a).reduce((z,t)=>z+n(t.markValue||t.size),0)}
function stats(s,a){const t=s.trades.filter(x=>x.accountId===a.id&&x.status==='closed'),wins=t.filter(x=>x.pnlUsd>0),p=t.reduce((z,x)=>z+n(x.pnlUsd),0),losses=t.filter(x=>x.pnlUsd<0),avgWin=wins.length?wins.reduce((z,x)=>z+x.pnlPct,0)/wins.length:0,avgLoss=losses.length?losses.reduce((z,x)=>z+x.pnlPct,0)/losses.length:0;return{n:t.length,w:wins.length,wr:t.length?wins.length/t.length*100:0,p,ret:a.start?p/a.start*100:0,avgWin,avgLoss}}
async function quote(token){const r=await fetch('/api/meme-scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q:token})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Price lookup failed');const p=(d.pairs||[]).sort((a,b)=>n(b.liquidityUsd)-n(a.liquidityUsd))[0];if(!p||!n(p.priceUsd))throw new Error('No live price found');return p}
function grade(t){let s=50;if(t.score>=80)s+=15;else if(t.score<60)s-=10;if(t.riskPct<=1)s+=10;else if(t.riskPct>2)s-=12;if(t.pnlPct>0)s+=10;else s-=8;if(t.exitReason==='target')s+=8;if(t.exitReason==='stop')s-=2;return Math.max(0,Math.min(100,Math.round(s)))}
function closeTrade(s,t,a,market,reason='manual'){const exitFill=market*(1-cfg.slipPct/100),gross=t.qty*exitFill,exitFee=gross*cfg.feePct/100,net=gross-exitFee,pnl=net-t.totalCost;t.exitMarket=market;t.exit=exitFill;t.exitFee=exitFee;t.pnlUsd=pnl;t.pnlPct=t.totalCost?pnl/t.totalCost*100:0;t.status='closed';t.exitReason=reason;t.closedAt=new Date().toISOString();t.grade=grade(t);a.balance+=net;return t}
async function refreshOpen(){const s=load(),a=acct(s),ots=openTrades(s,a);for(const t of ots){try{const p=await quote(t.token),m=n(p.priceUsd);t.lastMarket=m;t.markValue=t.qty*m;t.livePnlPct=t.totalCost?(t.markValue-t.totalCost)/t.totalCost*100:0;t.liquidityUsd=n(p.liquidityUsd);t.volume24h=n(p.volume24h);if(m<=t.stopPrice)closeTrade(s,t,a,m,'stop');else if(m>=t.targetPrice)closeTrade(s,t,a,m,'target')}catch(e){t.priceError=e.message}}save(s);return s}
function render(){window.JTablet?.open?.('money');const s=load(),a=acct(s),eq=equity(s,a),day=todayPnl(s,a),st=stats(s,a),ots=openTrades(s,a);body.innerHTML=`<div class="statusHero">AXIOM WATCH · FULL SIM</div><div class="muted">Live market training with virtual cash only. Fees ${cfg.feePct}%/side · slippage ${cfg.slipPct}%/side · max position ${cfg.maxPosPct}% equity · max ${cfg.maxOpen} open trades · daily loss guard ${cfg.dailyLossPct}%.</div><div style="display:flex;gap:7px;overflow:auto;margin:12px 0">${s.accounts.map(x=>`<button data-acct="${x.id}" style="flex:0 0 auto;background:${x.id===a.id?'#222':'#111'};border:1px solid #444;color:#fff;border-radius:999px;padding:8px 11px">${esc(x.name)} · ${usd(x.balance)}</button>`).join('')}</div><div class="tabletGrid"><button data-ax="discover"><b>Discover</b><span>Axiom trending</span></button><button data-ax="pulse"><b>Pulse</b><span>Live meme flow</span></button><button id="simRefresh"><b>Refresh Prices</b><span>Mark-to-market + auto exits</span></button><button data-ax="trackers"><b>Trackers</b><span>Wallet flow</span></button></div><div class="log"><b>${esc(a.name)} · EQUITY ${usd(eq)}</b><small>Cash ${usd(a.balance)} · Open ${ots.length}/${cfg.maxOpen} · Today ${day>=0?'+':''}${usd(day)} · Return ${st.ret>=0?'+':''}${st.ret.toFixed(2)}%</small></div><h4>SIM ENTRY</h4><div class="tabletGrid"><label>Token / CA<input id="ptToken"></label><label>Market price<input id="ptEntry" type="number" step="any"></label><label>Position $<input id="ptSize" type="number" value="25"></label><label>Stop %<input id="ptStop" type="number" value="10"></label><label>Target %<input id="ptTarget" type="number" value="20"></label><label>J Score<input id="ptScore" type="number" min="0" max="100"></label></div><div style="display:flex;gap:8px;margin-top:9px"><button id="getPrice" style="flex:1;background:#111;border:1px solid #333;color:#fff;border-radius:9px;padding:9px">GET LIVE PRICE</button><button id="ptOpen" style="flex:1;background:#171717;border:1px solid #444;color:#fff;border-radius:9px;padding:9px">BUY IN SIM</button></div><div id="simMsg" class="muted"></div><div id="ptBook"></div>`;
body.querySelectorAll('label').forEach(l=>{l.style.cssText='font-size:9px;color:#aaa;display:flex;flex-direction:column;gap:5px';l.querySelector('input').style.cssText='background:#0d0d0d;border:1px solid #333;color:#fff;border-radius:8px;padding:9px'});
const routes={discover:'/t/H9kr9cDFdhv3',pulse:'/pulse',trackers:'/trackers',vision:'/vision?chain=sol'};body.querySelectorAll('[data-ax]').forEach(b=>b.onclick=()=>openUrl(AXIOM+routes[b.dataset.ax]));body.querySelectorAll('[data-acct]').forEach(b=>b.onclick=()=>{const x=load();x.active=b.dataset.acct;save(x);render()});
body.querySelector('#getPrice').onclick=async()=>{const token=body.querySelector('#ptToken').value.trim(),m=body.querySelector('#simMsg');if(!token)return;m.textContent='Getting live price…';try{const p=await quote(token);body.querySelector('#ptEntry').value=p.priceUsd;m.textContent=`Live ${fmt(p.priceUsd)} · Liq ${usd(p.liquidityUsd)} · 24h vol ${usd(p.volume24h)}`}catch(e){m.textContent=e.message}};
body.querySelector('#simRefresh').onclick=async()=>{body.querySelector('#simMsg').textContent='Refreshing open positions…';await refreshOpen();render()};
body.querySelector('#ptOpen').onclick=()=>{const x=load(),aa=acct(x),token=body.querySelector('#ptToken').value.trim(),market=n(body.querySelector('#ptEntry').value),size=n(body.querySelector('#ptSize').value),stop=Math.abs(n(body.querySelector('#ptStop').value)),target=Math.abs(n(body.querySelector('#ptTarget').value)),score=n(body.querySelector('#ptScore').value),eq=equity(x,aa),day=todayPnl(x,aa),maxSize=eq*cfg.maxPosPct/100;if(!token||!market||!size)return alert('Token, price and size are required.');if(openTrades(x,aa).length>=cfg.maxOpen)return alert('Max open trades reached.');if(day<=-(aa.start*cfg.dailyLossPct/100))return alert('Daily loss guard is active. Stop trading this sim today.');if(size>maxSize)return alert(`Position too large. Max is ${usd(maxSize)} (${cfg.maxPosPct}% of equity).`);const entryFill=market*(1+cfg.slipPct/100),entryFee=size*cfg.feePct/100,totalCost=size+entryFee;if(totalCost>aa.balance)return alert('Not enough virtual cash.');const qty=size/entryFill,riskUsd=size*stop/100,riskPct=eq?riskUsd/eq*100:0;aa.balance-=totalCost;x.trades.unshift({id:Date.now(),accountId:aa.id,token,entryMarket:market,entry:entryFill,size,entryFee,totalCost,qty,stop,target,stopPrice:entryFill*(1-stop/100),targetPrice:entryFill*(1+target/100),score,riskUsd,riskPct,status:'open',openedAt:new Date().toISOString(),markValue:size});save(x);window.JSafety?.log?.('sim-trade',`BUY ${token} ${usd(size)} in ${aa.name}`);render()};
function draw(){const x=load(),aa=acct(x),tr=x.trades.filter(t=>t.accountId===aa.id),st=stats(x,aa),book=body.querySelector('#ptBook');book.innerHTML=`<div class="log" style="margin-top:12px"><b>J TRAINING SCOREBOARD</b><small>${st.n} closed · ${st.w} wins · ${st.wr.toFixed(1)}% win rate · Avg win ${st.avgWin.toFixed(1)}% · Avg loss ${st.avgLoss.toFixed(1)}% · P/L ${st.p>=0?'+':''}${usd(st.p)}</small></div><h4>TRADE JOURNAL</h4>`+(tr.length?tr.map(t=>`<div class="log"><b>${esc(t.token)} · ${t.status.toUpperCase()}${t.score?' · J '+t.score:''}${t.grade!=null?' · GRADE '+t.grade:''}</b><small>Fill ${fmt(t.entry)} · Size ${usd(t.size)} · Risk ${t.riskPct?.toFixed(2)||'0'}% · Stop ${fmt(t.stopPrice)} · Target ${fmt(t.targetPrice)}${t.status==='open'?` · Live ${t.livePnlPct>=0?'+':''}${(t.livePnlPct||0).toFixed(2)}%`:` · ${t.exitReason} · P/L ${t.pnlPct>=0?'+':''}${t.pnlPct.toFixed(2)}% (${t.pnlUsd>=0?'+':''}${usd(t.pnlUsd)})`}</small>${t.status==='open'?`<div style="display:flex;gap:6px;margin-top:7px"><input data-exit="${t.id}" placeholder="Current market price" type="number" step="any" style="flex:1;background:#0d0d0d;border:1px solid #333;color:#fff;border-radius:8px;padding:7px"><button data-close="${t.id}" style="background:#171717;border:1px solid #444;color:#fff;border-radius:8px">SELL SIM</button></div>`:''}</div>`).join(''):'<div class="muted">No trades yet.</div>';book.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const id=+b.dataset.close,market=n(book.querySelector(`[data-exit="${id}"]`)?.value);if(!market)return;const z=load(),t=z.trades.find(q=>q.id===id),acc=z.accounts.find(q=>q.id===t?.accountId);if(!t||!acc)return;closeTrade(z,t,acc,market,'manual');save(z);render()})}draw()}
window.JAxiom={render,open:openUrl,simState:load,refreshSim:refreshOpen};
})();