(()=>{
const body=document.getElementById('tabletBody');
if(!body)return;
const AXIOM='https://axiom.trade',KEY='j_axiom_paper_v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Number(x)||0,fmt=x=>Number(x||0).toLocaleString(undefined,{maximumFractionDigits:6});
function openUrl(url){window.JSafety?.log?.('axiom-open',url);window.open(url,'_blank','noopener,noreferrer')}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function save(v){localStorage.setItem(KEY,JSON.stringify(v.slice(0,100)))}
function stats(){const t=load().filter(x=>x.status==='closed'),wins=t.filter(x=>x.pnlPct>0),p=t.reduce((a,x)=>a+x.pnlPct,0);return{n:t.length,w:wins.length,wr:t.length?wins.length/t.length*100:0,p}}
function render(){window.JTablet?.open?.('money');body.innerHTML=`<div class="statusHero">AXIOM WATCH · PAPER MODE</div><div class="muted">Jay learns the workflow with simulated trades first. No wallet transaction, buy, sell, or Axiom order is submitted from this trainer.</div><div class="tabletGrid" style="margin-top:12px"><button data-ax="discover"><b>Discover</b><span>Trending / DEX surge</span></button><button data-ax="pulse"><b>Pulse</b><span>Live meme flow</span></button><button data-ax="trackers"><b>Trackers</b><span>Wallets / live trades</span></button><button data-ax="vision"><b>Vision</b><span>KOL / flow view</span></button></div><div class="log" style="margin-top:12px"><b>J TRADE CHECKLIST</b><small>1. Find candidate on Axiom. 2. Check liquidity + volume + buy/sell flow. 3. Avoid obvious vertical/chase entries. 4. Define invalidation before entry. 5. Paper-enter. 6. Record exit and learn.</small></div><h4>PAPER ENTRY</h4><div class="tabletGrid"><label>Token / CA<input id="ptToken"></label><label>Entry price<input id="ptEntry" type="number" step="any"></label><label>Paper size $<input id="ptSize" type="number" value="25" step="1"></label><label>Stop %<input id="ptStop" type="number" value="10" step="1"></label><label>Target 1 %<input id="ptT1" type="number" value="20" step="1"></label><label>J Score<input id="ptScore" type="number" min="0" max="100"></label></div><button id="ptOpen" style="margin-top:10px;width:100%;padding:11px;border-radius:10px;background:#171717;border:1px solid #444;color:#fff">OPEN PAPER TRADE</button><div id="ptBook"></div>`;
body.querySelectorAll('label').forEach(l=>{l.style.cssText='font-size:9px;color:#aaa;display:flex;flex-direction:column;gap:5px';const i=l.querySelector('input');i.style.cssText='background:#0d0d0d;border:1px solid #333;color:#fff;border-radius:8px;padding:9px'});
const routes={discover:'/t/H9kr9cDFdhv3',pulse:'/pulse',trackers:'/trackers',vision:'/vision?chain=sol'};body.querySelectorAll('[data-ax]').forEach(b=>b.onclick=()=>openUrl(AXIOM+routes[b.dataset.ax]));
body.querySelector('#ptOpen').onclick=()=>{const token=body.querySelector('#ptToken').value.trim(),entry=num(body.querySelector('#ptEntry').value),size=num(body.querySelector('#ptSize').value),stop=Math.abs(num(body.querySelector('#ptStop').value)),target=Math.abs(num(body.querySelector('#ptT1').value)),score=num(body.querySelector('#ptScore').value);if(!token||!entry||!size)return alert('Token, entry price and paper size are required.');const trade={id:Date.now(),token,entry,size,stop,target,score,status:'open',openedAt:new Date().toISOString()};const v=load();v.unshift(trade);save(v);window.JSafety?.log?.('paper-trade',`OPEN ${token} $${size} @ ${entry}`);draw()};
function draw(){const v=load(),s=stats(),book=body.querySelector('#ptBook');book.innerHTML=`<div class="log" style="margin-top:12px"><b>TRAINING SCOREBOARD</b><small>${s.n} closed · ${s.w} wins · ${s.wr.toFixed(1)}% win rate · cumulative ${s.p>=0?'+':''}${s.p.toFixed(1)}%</small></div><h4>TRADE JOURNAL</h4>`+(v.length?v.map(t=>`<div class="log"><b>${esc(t.token)} · ${t.status.toUpperCase()}${t.score?' · J '+t.score:''}</b><small>Entry ${fmt(t.entry)} · Paper $${fmt(t.size)} · Stop -${fmt(t.stop)}% · T1 +${fmt(t.target)}%${t.status==='closed'?` · Exit ${fmt(t.exit)} · P/L ${t.pnlPct>=0?'+':''}${fmt(t.pnlPct)}%`:''}</small>${t.status==='open'?`<div style="display:flex;gap:6px;margin-top:7px"><input data-exit="${t.id}" placeholder="Exit price" type="number" step="any" style="flex:1;background:#0d0d0d;border:1px solid #333;color:#fff;border-radius:8px;padding:7px"><button data-close="${t.id}" style="background:#171717;border:1px solid #444;color:#fff;border-radius:8px">Close paper trade</button></div>`:''}</div>`).join(''):'<div class="muted">No paper trades yet.</div>';book.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const id=+b.dataset.close,inp=book.querySelector(`[data-exit="${id}"]`),exit=num(inp?.value);if(!exit)return;const all=load(),t=all.find(x=>x.id===id);if(!t)return;t.exit=exit;t.pnlPct=(exit/t.entry-1)*100;t.pnlUsd=t.size*t.pnlPct/100;t.status='closed';t.closedAt=new Date().toISOString();save(all);window.JSafety?.log?.('paper-trade',`CLOSE ${t.token} ${t.pnlPct.toFixed(2)}%`);draw()})}
draw()}
window.JAxiom={render,open:openUrl,paperTrades:load};
})();
