(()=>{
const body=document.getElementById('tabletBody');
if(!body)return;
const AXIOM='https://axiom.trade',KEY='j_axiom_paper_v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Number(x)||0,fmt=x=>Number(x||0).toLocaleString(undefined,{maximumFractionDigits:6}),usd=x=>'$'+Number(x||0).toLocaleString(undefined,{maximumFractionDigits:2});
function openUrl(url){window.JSafety?.log?.('axiom-open',url);window.open(url,'_blank','noopener,noreferrer')}
function defaults(){return{active:'rookie',accounts:[{id:'rookie',name:'Rookie Sim',start:1000,balance:1000},{id:'scout',name:'Scout Sim',start:5000,balance:5000},{id:'pro',name:'Pro Sim',start:25000,balance:25000}],trades:[]}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');return d&&d.accounts?d:defaults()}catch{return defaults()}}
function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
function acct(s){return s.accounts.find(a=>a.id===s.active)||s.accounts[0]}
function stats(s,a){const t=s.trades.filter(x=>x.accountId===a.id&&x.status==='closed'),wins=t.filter(x=>x.pnlUsd>0),p=t.reduce((z,x)=>z+x.pnlUsd,0);return{n:t.length,w:wins.length,wr:t.length?wins.length/t.length*100:0,p,ret:a.start?p/a.start*100:0}}
function render(){window.JTablet?.open?.('money');const s=load(),a=acct(s);body.innerHTML=`<div class="statusHero">AXIOM WATCH · TRADING SIM</div><div class="muted">Virtual funded accounts only. Jay can train against Axiom flow without placing real orders or touching a wallet.</div><div style="display:flex;gap:7px;overflow:auto;margin:12px 0" id="simAccts">${s.accounts.map(x=>`<button data-acct="${x.id}" style="flex:0 0 auto;background:${x.id===a.id?'#222':'#111'};border:1px solid #444;color:#fff;border-radius:999px;padding:8px 11px">${esc(x.name)} · ${usd(x.balance)}</button>`).join('')}</div><div class="tabletGrid"><button data-ax="discover"><b>Discover</b><span>Trending / DEX surge</span></button><button data-ax="pulse"><b>Pulse</b><span>Live meme flow</span></button><button data-ax="trackers"><b>Trackers</b><span>Wallets / live trades</span></button><button data-ax="vision"><b>Vision</b><span>KOL / flow view</span></button></div><div class="log" style="margin-top:12px"><b>SIM ACCOUNT · ${esc(a.name)}</b><small>Starting ${usd(a.start)} · Current ${usd(a.balance)} · Available virtual cash only</small></div><h4>SIMULATED ENTRY</h4><div class="tabletGrid"><label>Token / CA<input id="ptToken"></label><label>Entry price<input id="ptEntry" type="number" step="any"></label><label>Position size $<input id="ptSize" type="number" value="25" step="1"></label><label>Stop %<input id="ptStop" type="number" value="10" step="1"></label><label>Target 1 %<input id="ptT1" type="number" value="20" step="1"></label><label>J Score<input id="ptScore" type="number" min="0" max="100"></label></div><button id="ptOpen" style="margin-top:10px;width:100%;padding:11px;border-radius:10px;background:#171717;border:1px solid #444;color:#fff">BUY IN SIM</button><div style="display:flex;gap:8px;margin-top:8px"><button id="simReset" style="flex:1;background:#111;border:1px solid #333;color:#fff;border-radius:9px;padding:9px">Reset Account</button><button id="simAdd" style="flex:1;background:#111;border:1px solid #333;color:#fff;border-radius:9px;padding:9px">Add Custom Sim</button></div><div id="ptBook"></div>`;
body.querySelectorAll('label').forEach(l=>{l.style.cssText='font-size:9px;color:#aaa;display:flex;flex-direction:column;gap:5px';const i=l.querySelector('input');i.style.cssText='background:#0d0d0d;border:1px solid #333;color:#fff;border-radius:8px;padding:9px'});
const routes={discover:'/t/H9kr9cDFdhv3',pulse:'/pulse',trackers:'/trackers',vision:'/vision?chain=sol'};body.querySelectorAll('[data-ax]').forEach(b=>b.onclick=()=>openUrl(AXIOM+routes[b.dataset.ax]));
body.querySelectorAll('[data-acct]').forEach(b=>b.onclick=()=>{const x=load();x.active=b.dataset.acct;save(x);render()});
body.querySelector('#simReset').onclick=()=>{const x=load(),aa=acct(x);aa.balance=aa.start;x.trades=x.trades.filter(t=>t.accountId!==aa.id);save(x);window.JSafety?.log?.('sim-reset',aa.name);render()};
body.querySelector('#simAdd').onclick=()=>{const name=prompt('Sim account name','Custom Sim'),funds=num(prompt('Starting virtual balance','10000'));if(!name||funds<=0)return;const x=load(),id='custom_'+Date.now();x.accounts.push({id,name,start:funds,balance:funds});x.active=id;save(x);render()};
body.querySelector('#ptOpen').onclick=()=>{const x=load(),aa=acct(x),token=body.querySelector('#ptToken').value.trim(),entry=num(body.querySelector('#ptEntry').value),size=num(body.querySelector('#ptSize').value),stop=Math.abs(num(body.querySelector('#ptStop').value)),target=Math.abs(num(body.querySelector('#ptT1').value)),score=num(body.querySelector('#ptScore').value);if(!token||!entry||!size)return alert('Token, entry price and position size are required.');if(size>aa.balance)return alert('Not enough virtual cash in this sim account.');aa.balance-=size;x.trades.unshift({id:Date.now(),accountId:aa.id,token,entry,size,stop,target,score,status:'open',openedAt:new Date().toISOString()});save(x);window.JSafety?.log?.('sim-trade',`BUY ${token} ${usd(size)} @ ${entry} in ${aa.name}`);render()};
function draw(){const x=load(),aa=acct(x),st=stats(x,aa),tr=x.trades.filter(t=>t.accountId===aa.id),book=body.querySelector('#ptBook');book.innerHTML=`<div class="log" style="margin-top:12px"><b>ACCOUNT SCOREBOARD</b><small>${st.n} closed · ${st.w} wins · ${st.wr.toFixed(1)}% win rate · P/L ${st.p>=0?'+':''}${usd(st.p)} · Return ${st.ret>=0?'+':''}${st.ret.toFixed(2)}%</small></div><h4>TRADE JOURNAL</h4>`+(tr.length?tr.map(t=>`<div class="log"><b>${esc(t.token)} · ${t.status.toUpperCase()}${t.score?' · J '+t.score:''}</b><small>Entry ${fmt(t.entry)} · Size ${usd(t.size)} · Stop -${fmt(t.stop)}% · T1 +${fmt(t.target)}%${t.status==='closed'?` · Exit ${fmt(t.exit)} · P/L ${t.pnlPct>=0?'+':''}${fmt(t.pnlPct)}% (${t.pnlUsd>=0?'+':''}${usd(t.pnlUsd)})`:''}</small>${t.status==='open'?`<div style="display:flex;gap:6px;margin-top:7px"><input data-exit="${t.id}" placeholder="Exit price" type="number" step="any" style="flex:1;background:#0d0d0d;border:1px solid #333;color:#fff;border-radius:8px;padding:7px"><button data-close="${t.id}" style="background:#171717;border:1px solid #444;color:#fff;border-radius:8px">SELL IN SIM</button></div>`:''}</div>`).join(''):'<div class="muted">No simulated trades yet.</div>';book.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const id=+b.dataset.close,inp=book.querySelector(`[data-exit="${id}"]`),exit=num(inp?.value);if(!exit)return;const z=load(),t=z.trades.find(q=>q.id===id),acc=z.accounts.find(q=>q.id===t?.accountId);if(!t||!acc)return;t.exit=exit;t.pnlPct=(exit/t.entry-1)*100;t.pnlUsd=t.size*t.pnlPct/100;t.status='closed';t.closedAt=new Date().toISOString();acc.balance+=t.size+t.pnlUsd;save(z);window.JSafety?.log?.('sim-trade',`SELL ${t.token} ${t.pnlPct.toFixed(2)}% in ${acc.name}`);render()})}
draw()}
window.JAxiom={render,open:openUrl,simState:load};
})();
