(()=>{
const body=document.getElementById('tabletBody'),tabsWrap=document.querySelector('.tabletTabs');if(!body||!tabsWrap)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const money=n=>Number.isFinite(Number(n))?'$'+Number(n).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
function addTab(id,label){if(document.querySelector(`[data-jgrowth="${id}"]`))return;const b=document.createElement('button');b.dataset.jgrowth=id;b.textContent=label;tabsWrap.appendChild(b);b.addEventListener('click',e=>{e.stopImmediatePropagation();document.querySelectorAll('.tabletTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');id==='meta'?renderMeta():renderMeme()},{capture:true})}
addTab('meta','META ADS');addTab('meme','MEME WATCH');
function scorePair(p){let s=45;const reasons=[],risks=[];const liq=+p.liquidityUsd||0,vol=+p.volume24h||0,v1=+p.volume1h||0,mc=+p.marketCap||+p.fdv||0,buys=+p.buys24h||0,sells=+p.sells24h||0,b1=+p.buys1h||0,s1=+p.sells1h||0,c1=+p.change1h||0,c24=+p.change24h||0,age=p.pairCreatedAt?Date.now()-Number(p.pairCreatedAt):null;
if(liq>=250000){s+=14;reasons.push('strong liquidity')}else if(liq>=75000){s+=8;reasons.push('usable liquidity')}else if(liq<25000){s-=20;risks.push('thin liquidity')}else{s-=7;risks.push('limited liquidity')}
if(vol>=500000){s+=12;reasons.push('high 24h volume')}else if(vol>=100000)s+=6;else if(vol<25000){s-=10;risks.push('low volume')}
if(v1>=50000){s+=6;reasons.push('active 1h volume')}if(b1>s1*1.35&&b1>=10){s+=8;reasons.push('fresh buy pressure')}else if(s1>b1*1.5&&s1>=10){s-=10;risks.push('fresh sell pressure')}
if(buys>sells*1.2&&buys>30){s+=6;reasons.push('24h buy pressure')}else if(sells>buys*1.45&&sells>20){s-=8;risks.push('24h sell pressure')}
if(c1>3&&c1<30){s+=7;reasons.push('healthy 1h momentum')}else if(c1>50){s-=12;risks.push('parabolic 1h move')}else if(c1<-20){s-=8;risks.push('sharp 1h drop')}
if(c24>10&&c24<150){s+=5;reasons.push('positive daily trend')}else if(c24>300){s-=10;risks.push('extreme 24h move')}
if(mc&&liq/mc<.025){s-=9;risks.push('low liquidity vs market cap')}if(age!==null&&age<3600000){s-=12;risks.push('under 1 hour old')}else if(age!==null&&age<86400000){s-=5;risks.push('under 24 hours old')}
if(p.hasWebsite){s+=2;reasons.push('website listed')}if(+p.socialCount>=2){s+=2;reasons.push('social presence')}if(+p.boostTotal>0){reasons.push('paid boost detected')}
s=Math.max(0,Math.min(100,Math.round(s)));return{score:s,reasons,risks,label:s>=80?'STRONG WATCH':s>=68?'WATCH':s>=52?'NEUTRAL':'HIGH RISK'}}
function getWatch(){try{return JSON.parse(localStorage.getItem('j_meme_watch_v1')||'[]')}catch{return[]}}function setWatch(v){localStorage.setItem('j_meme_watch_v1',JSON.stringify(v.slice(0,20)))}
async function scan(q){const r=await fetch('/api/meme-scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Scan failed');return d}
async function discover(){const r=await fetch('/api/meme-discover');const d=await r.json();if(!r.ok)throw new Error(d.error||'Discovery failed');return d}
function card(p,i){return `<div class="log"><b>${i+1}. ${esc(p.baseToken?.symbol||p.baseToken?.name||'TOKEN')} · J SCORE ${p.score}/100 · ${p.label}</b><small>${esc(p.chainId)} · ${esc(p.dexId)} · Price ${money(p.priceUsd)} · Liquidity ${money(p.liquidityUsd)} · 1h Vol ${money(p.volume1h)} · 24h Vol ${money(p.volume24h)} · 1h ${fmt(p.change1h)}% · 24h ${fmt(p.change24h)}%</small><small>${p.reasons.length?'Why: '+esc(p.reasons.join(', ')):''}${p.risks.length?' · Risks: '+esc(p.risks.join(', ')):''}</small><button data-save="${esc(p.baseToken?.address||'')}" style="margin-top:7px;background:#111;border:1px solid #333;color:#fff;border-radius:8px;padding:6px 8px">Add to watchlist</button></div>`}
async function renderMeme(){body.innerHTML=`<div class="statusHero">MEME WATCH · AUTO DISCOVERY</div><div class="muted">J scans fresh profiles and heavily boosted tokens, then ranks them. This is market research, not a guarantee or buy signal. Trading stays approval-only.</div><div style="display:flex;gap:8px;margin:12px 0"><button id="jdiscover" style="flex:1;background:#171717;border:1px solid #444;color:white;border-radius:10px;padding:10px 12px">Discover Now</button><input id="jmemeq" placeholder="Symbol, name, or contract" style="flex:1;background:#0d0d0d;border:1px solid #333;color:white;border-radius:10px;padding:10px"><button id="jmemescan" style="background:#171717;border:1px solid #444;color:white;border-radius:10px;padding:10px 12px">Scan</button></div><div id="jmemeresults"></div><h4>WATCHLIST</h4><div id="jmemeWatch"></div>`;
const q=body.querySelector('#jmemeq'),results=body.querySelector('#jmemeresults'),watchEl=body.querySelector('#jmemeWatch');
function drawWatch(){const w=getWatch();watchEl.innerHTML=w.length?w.map(x=>`<button data-w="${esc(x)}" style="margin:4px;background:#111;border:1px solid #333;color:#fff;border-radius:999px;padding:7px 10px">${esc(x)}</button>`).join(''):'<div class="muted">No coins saved yet.</div>';watchEl.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{q.value=b.dataset.w;doScan()})}
function bindSave(){results.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{if(!b.dataset.save)return;const w=getWatch();if(!w.includes(b.dataset.save)){w.unshift(b.dataset.save);setWatch(w)}drawWatch();window.JSafety?.log?.('meme-watch',`Added ${b.dataset.save}`)})}
async function doScan(){const term=q.value.trim();if(!term)return;results.innerHTML='<div class="tload">SCANNING MARKET…</div>';try{const d=await scan(term);const ranked=(d.pairs||[]).map(p=>({...p,...scorePair(p)})).sort((a,b)=>b.score-a.score).slice(0,8);results.innerHTML=ranked.length?ranked.map(card).join(''):'<div class="muted">No pairs found.</div>';bindSave();window.JSafety?.log?.('meme-scan',`${term}: ${ranked.length} ranked pairs`)}catch(e){results.innerHTML=`<div class="statusHero bad">SCAN FAILED</div><div class="muted">${esc(e.message)}</div>`}}
async function doDiscover(){results.innerHTML='<div class="tload">J IS HUNTING THE MARKET…</div>';try{const d=await discover();const ranked=(d.candidates||[]).map(p=>({...p,...scorePair(p)})).filter(p=>p.score>=52).sort((a,b)=>b.score-a.score||b.volume1h-a.volume1h).slice(0,12);const strong=ranked.filter(x=>x.score>=80).length;results.innerHTML=`<div class="trow"><span>Scan time</span><b>${new Date(d.scannedAt).toLocaleTimeString()}</b></div><div class="trow"><span>Qualified</span><b>${ranked.length}</b></div><div class="trow"><span>Strong watch</span><b>${strong}</b></div>`+(ranked.length?ranked.map(card).join(''):'<div class="muted">Nothing met J’s minimum quality filter in this scan.</div>');bindSave();window.JSafety?.log?.('meme-discover',`${ranked.length} qualified; ${strong} strong`)}catch(e){results.innerHTML=`<div class="statusHero bad">DISCOVERY FAILED</div><div class="muted">${esc(e.message)}</div>`}}
body.querySelector('#jdiscover').onclick=doDiscover;body.querySelector('#jmemescan').onclick=doScan;q.addEventListener('keydown',e=>{if(e.key==='Enter')doScan()});drawWatch();doDiscover()}
function metaGrade(m){let score=50,notes=[];if(m.ctr>=2){score+=12;notes.push('CTR is strong')}else if(m.ctr<1){score-=12;notes.push('CTR is weak — creative/hook likely needs work')};if(m.cpm&&m.cpm<18){score+=7;notes.push('CPM is efficient')}else if(m.cpm>35){score-=7;notes.push('CPM is expensive')};if(m.cpa&&m.targetCpa){if(m.cpa<=m.targetCpa){score+=15;notes.push('CPA is at/under target')}else{score-=15;notes.push('CPA is above target')}};if(m.roas>=3){score+=16;notes.push('ROAS is strong')}else if(m.roas>0&&m.roas<1.5){score-=14;notes.push('ROAS is weak')};score=Math.max(0,Math.min(100,Math.round(score)));return{score,notes}}
function renderMeta(){body.innerHTML=`<div class="statusHero">META ADS BRAIN · TRAINING MODE</div><div class="muted">Feed J campaign metrics and he will diagnose what to test. Live account changes will require approval once Meta is connected.</div><div class="tabletGrid" style="margin-top:12px"><label>Spend<input id="mSpend" type="number" step="0.01"></label><label>Revenue<input id="mRev" type="number" step="0.01"></label><label>Impressions<input id="mImp" type="number"></label><label>Clicks<input id="mClicks" type="number"></label><label>Purchases<input id="mPurch" type="number"></label><label>Target CPA<input id="mTarget" type="number" step="0.01"></label></div><button id="mAnalyze" style="margin-top:12px;width:100%;background:#171717;border:1px solid #444;color:white;border-radius:10px;padding:11px">Analyze Campaign</button><div id="mOut" style="margin-top:12px"></div>`;body.querySelectorAll('label').forEach(l=>{l.style.cssText='font-size:9px;color:#aaa;display:flex;flex-direction:column;gap:5px';const i=l.querySelector('input');if(i)i.style.cssText='background:#0d0d0d;border:1px solid #333;color:white;border-radius:8px;padding:9px'});body.querySelector('#mAnalyze').onclick=()=>{const spend=+body.querySelector('#mSpend').value||0,rev=+body.querySelector('#mRev').value||0,imp=+body.querySelector('#mImp').value||0,clicks=+body.querySelector('#mClicks').value||0,p=+body.querySelector('#mPurch').value||0,targetCpa=+body.querySelector('#mTarget').value||0;const ctr=imp?clicks/imp*100:0,cpm=imp?spend/imp*1000:0,cpc=clicks?spend/clicks:0,cpa=p?spend/p:0,roas=spend?rev/spend:0;const g=metaGrade({ctr,cpm,cpa,targetCpa,roas});let action='Keep collecting data';if(ctr<1)action='Test new hooks/creative before increasing spend';else if(p===0&&clicks>=50)action='Check landing page, offer, pixel/CAPI and checkout friction';else if(targetCpa&&cpa>targetCpa)action='Reduce weak ad sets and test creative/audience before scaling';else if(roas>=3&&p>=3)action='Candidate for controlled scaling; increase budget gradually and watch CPA';body.querySelector('#mOut').innerHTML=`<div class="statusHero ${g.score>=70?'ok':g.score<50?'bad':''}">J ADS SCORE ${g.score}/100</div><div class="trow"><span>CTR</span><b>${fmt(ctr)}%</b></div><div class="trow"><span>CPM</span><b>${money(cpm)}</b></div><div class="trow"><span>CPC</span><b>${money(cpc)}</b></div><div class="trow"><span>CPA</span><b>${p?money(cpa):'NO SALES'}</b></div><div class="trow"><span>ROAS</span><b>${fmt(roas)}x</b></div><div class="log"><b>NEXT MOVE</b><small>${esc(action)}</small></div><div class="muted">${esc(g.notes.join(' · '))}</div>`;window.JSafety?.log?.('meta-analysis',`Ads score ${g.score}/100`)}}
window.JGrowth={renderMeta,renderMeme,scanMeme:scan,discoverMeme:discover,scorePair};
})();
