(()=>{
const body=document.getElementById('tabletBody'),tabsWrap=document.querySelector('.tabletTabs');
if(!body||!tabsWrap)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const money=n=>Number.isFinite(Number(n))?'$'+Number(n).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
function addTab(id,label){if(document.querySelector(`[data-jgrowth="${id}"]`))return;const b=document.createElement('button');b.dataset.jgrowth=id;b.textContent=label;tabsWrap.appendChild(b);b.addEventListener('click',e=>{e.stopImmediatePropagation();document.querySelectorAll('.tabletTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');id==='meta'?renderMeta():renderMeme()},{capture:true})}
addTab('meta','META ADS');addTab('meme','MEME WATCH');
function scorePair(p){let s=50;const reasons=[],risks=[];const liq=+p.liquidityUsd||0,vol=+p.volume24h||0,mc=+p.marketCap||+p.fdv||0,buys=+p.buys24h||0,sells=+p.sells24h||0,c1=+p.change1h||0,c24=+p.change24h||0;
if(liq>=250000){s+=12;reasons.push('strong liquidity')}else if(liq>=75000){s+=6;reasons.push('usable liquidity')}else{ s-=18;risks.push('thin liquidity') }
if(vol>=500000){s+=12;reasons.push('high 24h volume')}else if(vol>=100000)s+=5;else if(vol<25000){s-=10;risks.push('low volume')}
if(buys>sells*1.25&&buys>20){s+=8;reasons.push('buy pressure')}else if(sells>buys*1.4&&sells>20){s-=10;risks.push('sell pressure')}
if(c1>3&&c1<35){s+=6;reasons.push('1h momentum')}else if(c1>50){s-=8;risks.push('parabolic 1h move')}
if(c24>10&&c24<150){s+=5;reasons.push('positive daily trend')}else if(c24>300){s-=10;risks.push('extreme 24h move')}
if(mc&&liq/mc<.03){s-=8;risks.push('low liquidity vs market cap')}
if(p.pairCreatedAt&&Date.now()-Number(p.pairCreatedAt)<86400000){s-=6;risks.push('very new pair')}
s=Math.max(0,Math.min(100,Math.round(s)));return{score:s,reasons,risks,label:s>=80?'STRONG WATCH':s>=65?'WATCH':s>=50?'NEUTRAL':'HIGH RISK'}}
function getWatch(){try{return JSON.parse(localStorage.getItem('j_meme_watch_v1')||'[]')}catch{return[]}}
function setWatch(v){localStorage.setItem('j_meme_watch_v1',JSON.stringify(v.slice(0,12)))}
async function scan(q){const r=await fetch('/api/meme-scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Scan failed');return d}
async function renderMeme(){body.innerHTML=`<div class="statusHero">MEME WATCH · READ ONLY</div><div class="muted">J can scan and rank meme coins. Trading stays approval-only.</div><div style="display:flex;gap:8px;margin:12px 0"><input id="jmemeq" placeholder="Symbol, name, or contract" style="flex:1;background:#0d0d0d;border:1px solid #333;color:white;border-radius:10px;padding:10px"><button id="jmemescan" style="background:#171717;border:1px solid #444;color:white;border-radius:10px;padding:10px 12px">Scan</button></div><div id="jmemeresults"></div><h4>WATCHLIST</h4><div id="jmemeWatch"></div>`;
const q=body.querySelector('#jmemeq'),results=body.querySelector('#jmemeresults'),watchEl=body.querySelector('#jmemeWatch');
function drawWatch(){const w=getWatch();watchEl.innerHTML=w.length?w.map(x=>`<button data-w="${esc(x)}" style="margin:4px;background:#111;border:1px solid #333;color:#fff;border-radius:999px;padding:7px 10px">${esc(x)}</button>`).join(''):'<div class="muted">No coins saved yet.</div>';watchEl.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{q.value=b.dataset.w;doScan()})}
async function doScan(){const term=q.value.trim();if(!term)return;results.innerHTML='<div class="tload">SCANNING MARKET…</div>';try{const d=await scan(term);const ranked=(d.pairs||[]).map(p=>({...p,...scorePair(p)})).sort((a,b)=>b.score-a.score).slice(0,6);results.innerHTML=ranked.length?ranked.map((p,i)=>`<div class="log"><b>${i+1}. ${esc(p.baseToken?.symbol||p.baseToken?.name||'TOKEN')} · J SCORE ${p.score}/100 · ${p.label}</b><small>${esc(p.chainId)} · ${esc(p.dexId)} · Price ${money(p.priceUsd)} · Liquidity ${money(p.liquidityUsd)} · 24h Vol ${money(p.volume24h)} · 1h ${fmt(p.change1h)}% · 24h ${fmt(p.change24h)}%</small><small>${p.reasons.length?'Why: '+esc(p.reasons.join(', ')):''}${p.risks.length?' · Risks: '+esc(p.risks.join(', ')):''}</small><button data-save="${esc(p.baseToken?.address||term)}" style="margin-top:7px;background:#111;border:1px solid #333;color:#fff;border-radius:8px;padding:6px 8px">Add to watchlist</button></div>`).join(''):'<div class="muted">No pairs found.</div>';results.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const w=getWatch();if(!w.includes(b.dataset.save)){w.unshift(b.dataset.save);setWatch(w)}drawWatch();window.JSafety?.log?.('meme-watch',`Added ${b.dataset.save}`)});window.JSafety?.log?.('meme-scan',`${term}: ${ranked.length} ranked pairs`)}catch(e){results.innerHTML=`<div class="statusHero bad">SCAN FAILED</div><div class="muted">${esc(e.message)}</div>`}}
body.querySelector('#jmemescan').onclick=doScan;q.addEventListener('keydown',e=>{if(e.key==='Enter')doScan()});drawWatch()}
function metaGrade(m){let score=50,notes=[];if(m.ctr>=2){score+=12;notes.push('CTR is strong')}else if(m.ctr<1){score-=12;notes.push('CTR is weak — creative/hook likely needs work')};if(m.cpm&&m.cpm<18){score+=7;notes.push('CPM is efficient')}else if(m.cpm>35){score-=7;notes.push('CPM is expensive')};if(m.cpa&&m.targetCpa){if(m.cpa<=m.targetCpa){score+=15;notes.push('CPA is at/under target')}else{score-=15;notes.push('CPA is above target')}};if(m.roas>=3){score+=16;notes.push('ROAS is strong')}else if(m.roas>0&&m.roas<1.5){score-=14;notes.push('ROAS is weak')};score=Math.max(0,Math.min(100,Math.round(score)));return{score,notes}}
function renderMeta(){body.innerHTML=`<div class="statusHero">META ADS BRAIN · TRAINING MODE</div><div class="muted">Feed J campaign metrics and he will diagnose what to test. Live account changes will require approval once Meta is connected.</div><div class="tabletGrid" style="margin-top:12px"><label>Spend<input id="mSpend" type="number" step="0.01"></label><label>Revenue<input id="mRev" type="number" step="0.01"></label><label>Impressions<input id="mImp" type="number"></label><label>Clicks<input id="mClicks" type="number"></label><label>Purchases<input id="mPurch" type="number"></label><label>Target CPA<input id="mTarget" type="number" step="0.01"></label></div><button id="mAnalyze" style="margin-top:12px;width:100%;background:#171717;border:1px solid #444;color:white;border-radius:10px;padding:11px">Analyze Campaign</button><div id="mOut" style="margin-top:12px"></div>`;
body.querySelectorAll('label').forEach(l=>{l.style.cssText='font-size:9px;color:#aaa;display:flex;flex-direction:column;gap:5px';const i=l.querySelector('input');if(i)i.style.cssText='background:#0d0d0d;border:1px solid #333;color:white;border-radius:8px;padding:9px'});
body.querySelector('#mAnalyze').onclick=()=>{const spend=+body.querySelector('#mSpend').value||0,rev=+body.querySelector('#mRev').value||0,imp=+body.querySelector('#mImp').value||0,clicks=+body.querySelector('#mClicks').value||0,p=+body.querySelector('#mPurch').value||0,targetCpa=+body.querySelector('#mTarget').value||0;const ctr=imp?clicks/imp*100:0,cpm=imp?spend/imp*1000:0,cpc=clicks?spend/clicks:0,cpa=p?spend/p:0,roas=spend?rev/spend:0;const g=metaGrade({ctr,cpm,cpa,targetCpa,roas});let action='Keep collecting data';if(ctr<1)action='Test new hooks/creative before increasing spend';else if(p===0&&clicks>=50)action='Check landing page, offer, pixel/CAPI and checkout friction';else if(targetCpa&&cpa>targetCpa)action='Reduce weak ad sets and test creative/audience before scaling';else if(roas>=3&&p>=3)action='Candidate for controlled scaling; increase budget gradually and watch CPA';body.querySelector('#mOut').innerHTML=`<div class="statusHero ${g.score>=70?'ok':g.score<50?'bad':''}">J ADS SCORE ${g.score}/100</div><div class="trow"><span>CTR</span><b>${fmt(ctr)}%</b></div><div class="trow"><span>CPM</span><b>${money(cpm)}</b></div><div class="trow"><span>CPC</span><b>${money(cpc)}</b></div><div class="trow"><span>CPA</span><b>${p?money(cpa):'NO SALES'}</b></div><div class="trow"><span>ROAS</span><b>${fmt(roas)}x</b></div><div class="log"><b>NEXT MOVE</b><small>${esc(action)}</small></div><div class="muted">${esc(g.notes.join(' · '))}</div>`;window.JSafety?.log?.('meta-analysis',`Ads score ${g.score}/100`)} }
window.JGrowth={renderMeta,renderMeme,scanMeme:scan,scorePair};
})();
