(()=>{
  const tablet=document.getElementById('jTablet'),body=document.getElementById('tabletBody');
  if(!tablet||!body)return;
  let stream=null,mode=null,lastReply='';
  const style=document.createElement('style');style.textContent=`.visionWrap{display:grid;gap:10px}.visionStage{position:relative;aspect-ratio:16/9;background:#030303;border:1px solid #ffffff20;border-radius:14px;overflow:hidden}.visionStage video{width:100%;height:100%;object-fit:contain;background:#000}.visionBadge{position:absolute;left:10px;top:10px;padding:6px 8px;border:1px solid #ffffff25;border-radius:999px;background:#050505d9;font-size:9px;font-weight:800;letter-spacing:.08em}.visionGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.visionGrid button,.visionAsk{border:1px solid #ffffff22;background:#111;color:#fff;border-radius:12px;padding:11px;font-size:10px;font-weight:800}.visionAsk{width:100%;text-align:left}.visionReply{padding:12px;border:1px solid #ffffff1f;border-radius:12px;background:#0b0b0b;color:#ddd;font-size:11px;line-height:1.45;white-space:pre-wrap}.visionNote{font-size:9px;color:#888;line-height:1.45}`;document.head.appendChild(style);
  function stop(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}mode=null;render()}
  async function startCamera(){stop();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});mode='camera';render()}
  async function startScreen(){stop();if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Screen sharing is not supported in this browser. Try J on your computer, or use Camera Vision on iPhone.');stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});mode='screen';stream.getVideoTracks()[0]?.addEventListener('ended',stop);render()}
  function capture(){if(!stream)return null;const video=body.querySelector('.visionStage video');if(!video||!video.videoWidth)return null;const max=1280,scale=Math.min(1,max/video.videoWidth),c=document.createElement('canvas');c.width=Math.max(1,Math.round(video.videoWidth*scale));c.height=Math.max(1,Math.round(video.videoHeight*scale));c.getContext('2d').drawImage(video,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.82)}
  async function analyze(question){const image=capture();if(!image)throw new Error('Start the camera or screen first.');const r=await fetch('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,question})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Vision analysis failed');lastReply=d.reply||'';render();await window.speak?.(lastReply,{continueConversation:false});return d}
  function render(){
    if(window.JTabletVisionTab!==true)return;
    const active=Boolean(stream);body.innerHTML=`<div class="visionWrap"><div class="statusHero ${active?'ok':''}">J VISION ${active?'LIVE':'READY'}</div><div class="visionStage">${active?'<video autoplay muted playsinline></video>':'<div class="mediaEmpty">Share your camera or screen with J.<small>J only analyzes a frame when you tap Analyze.</small></div>'}${active?`<div class="visionBadge">${mode==='screen'?'SCREEN':'CAMERA'} LIVE</div>`:''}</div><div class="visionGrid"><button data-vcam>Camera Vision</button><button data-vscreen>Share Screen</button><button data-vanalyze>Analyze Now</button><button data-vstop>Stop</button></div><button class="visionAsk" data-vask>Ask J: “What am I looking at?”</button>${lastReply?`<div class="visionReply">${escapeHtml(lastReply)}</div>`:''}<div class="visionNote">Camera/screen access requires your device permission. J does not click, type, send, purchase, or change settings from Vision Mode without a separate approved action.</div></div>`;
    if(active){const v=body.querySelector('video');if(v)v.srcObject=stream}
    body.querySelector('[data-vcam]')?.addEventListener('click',()=>startCamera().catch(showErr));
    body.querySelector('[data-vscreen]')?.addEventListener('click',()=>startScreen().catch(showErr));
    body.querySelector('[data-vanalyze]')?.addEventListener('click',()=>analyze('Analyze this current frame. Tell me what is visible and what I should know.').catch(showErr));
    body.querySelector('[data-vask]')?.addEventListener('click',()=>analyze('What am I looking at? Explain the important parts clearly.').catch(showErr));
    body.querySelector('[data-vstop]')?.addEventListener('click',stop);
  }
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function showErr(e){lastReply=e?.message||'Vision failed.';render();window.speak?.(lastReply,{continueConversation:false})}
  const tabs=document.querySelector('.tabletTabs');if(tabs&&!tabs.querySelector('[data-jtab="vision"]')){const b=document.createElement('button');b.dataset.jtab='vision';b.textContent='VISION';tabs.appendChild(b);b.addEventListener('click',()=>{document.querySelectorAll('[data-jtab]').forEach(x=>x.classList.toggle('active',x===b));window.JTabletVisionTab=true;tablet.classList.add('open');render()})}
  const oldOpen=window.JTablet?.open;if(oldOpen){window.JTablet.open=function(tab){window.JTabletVisionTab=tab==='vision';if(tab==='vision'){tablet.classList.add('open');render();return}return oldOpen(tab)}}
  const oldAsk=window.ask;if(typeof oldAsk==='function'){window.ask=async function(text){const t=String(text||'').toLowerCase();if(/\b(vision|camera vision|share (my )?screen|screen mode)\b/.test(t)){window.JTablet?.open?.('vision');if(/share (my )?screen/.test(t)){try{await startScreen()}catch(e){showErr(e)}}else if(/camera/.test(t)){try{await startCamera()}catch(e){showErr(e)}}return}return oldAsk(text)}}
  window.JVision={startCamera,startScreen,stop,analyze,render};
})();
