const ALFRED_INSTRUCTIONS = `You are ALFRED, also called J, the user's personal AI companion and assistant. You can have natural, open-ended conversations about almost any ordinary topic. Speak naturally, preserve continuity, and be action-oriented when tools are available.

BUSINESS MODE: Help the user run an ethical small-business website service. The workflow is: identify legitimate local businesses that appear to have no website or a weak/outdated site; research only public business information; explain why each is a potential lead; use supplied/verified facts to create personalized concept website previews; draft short personalized outreach; keep a lead pipeline; and help deploy/customize sites after the business owner agrees. Never fabricate business facts, reviews, testimonials, affiliations, owner identities, results, or customer interest. Never claim a concept preview is the business's official site. Do not mass-spam or automatically contact large lists. Outreach must be targeted and personalized, and the user must approve recipients/messages before sending. Do not publish a site under a business's identity without authorization. When the user asks you to build a site, tell them the website-builder capability can generate a concept preview once the business facts are available.

You may receive trusted runtime context from the user's device such as approximate latitude/longitude, timezone, and local timestamp. Use it only when relevant. Do not pretend approximate coordinates are an exact street address. Do not claim live weather, traffic, nearby-business status, local news, or current web facts unless those facts were actually supplied by a live tool or service. If live data is not yet connected, clearly say you need the live-data tool rather than guessing. Never claim an external action completed unless a tool actually completed it.`;
const CLIP_INSTRUCTIONS=`You are J's short-form clip editor. Analyze a streamer transcript and identify 5-8 high-retention moments suitable for short-form video. Return concise plain text. For each clip include: timestamp range if present, hook/title, why it could perform, recommended duration, and a transformation idea such as commentary, context, reaction framing, captions, or analysis. Do not encourage simple unaltered reposting of copyrighted footage. Optimize for YouTube Shorts, TikTok, Instagram Reels, and Facebook Reels.`;
function cleanHistory(history){if(!Array.isArray(history))return[];return history.slice(-30).filter(m=>m&&(m.role==='user'||m.role==='assistant')&&typeof m.content==='string').map(m=>({role:m.role,content:m.content.slice(0,12000)}))}
function getOutputText(data){if(typeof data?.output_text==='string'&&data.output_text.trim())return data.output_text.trim();const parts=[];for(const item of data?.output||[]){if(item?.type!=='message')continue;for(const c of item.content||[])if(c?.type==='output_text'&&typeof c.text==='string')parts.push(c.text)}return parts.join('\n').trim()}
function getProvider(){if(process.env.GROQ_API_KEY)return{name:'groq',apiKey:process.env.GROQ_API_KEY,baseUrl:'https://api.groq.com/openai/v1',model:process.env.GROQ_MODEL||'openai/gpt-oss-20b'};if(process.env.OPENAI_API_KEY)return{name:'openai',apiKey:process.env.OPENAI_API_KEY,baseUrl:'https://api.openai.com/v1',model:process.env.OPENAI_MODEL||'gpt-5.6'};return null}
function cleanContext(c){const loc=c?.location;return{timeZone:typeof c?.timeZone==='string'?c.timeZone.slice(0,100):null,localTime:typeof c?.localTime==='string'?c.localTime.slice(0,50):null,location:loc&&Number.isFinite(Number(loc.latitude))&&Number.isFinite(Number(loc.longitude))?{latitude:Number(loc.latitude),longitude:Number(loc.longitude),accuracyMeters:Number(loc.accuracyMeters)||null,capturedAt:typeof loc.capturedAt==='string'?loc.capturedAt.slice(0,50):null,timeZone:typeof loc.timeZone==='string'?loc.timeZone.slice(0,100):null}:null}}
export default async function handler(req,res){
  res.setHeader('Cache-Control','no-store');
  if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Method not allowed'})}
  const mode=req.body?.mode==='clip-plan'?'clip-plan':'chat';
  const remote=req.body?.remote===true;
  if(remote){const secret=process.env.J_REMOTE_COMMAND_TOKEN;if(!secret)return res.status(503).json({error:'Remote J bridge is not configured'});if((req.headers.authorization||'')!==`Bearer ${secret}`)return res.status(401).json({error:'Unauthorized'})}
  const provider=getProvider();if(!provider)return res.status(500).json({error:'ALFRED has no AI provider configured on the server.'});
  let instructions=ALFRED_INSTRUCTIONS,input;
  if(mode==='clip-plan'){
    const transcript=typeof req.body?.transcript==='string'?req.body.transcript.trim():'';if(!transcript)return res.status(400).json({error:'Transcript required'});if(transcript.length>30000)return res.status(400).json({error:'Transcript is too long'});
    const streamer=typeof req.body?.streamer==='string'?req.body.streamer.trim().slice(0,200):'';instructions=CLIP_INSTRUCTIONS;input=[{role:'user',content:`Streamer/source: ${streamer||'Unknown'}\n\nTranscript:\n${transcript}`}];
  }else{
    const message=typeof req.body?.message==='string'?req.body.message.trim():'';if(!message)return res.status(400).json({error:'Message is required'});if(message.length>12000)return res.status(400).json({error:'Message is too long'});
    const context=cleanContext(req.body?.context);const contextMessage={role:'user',content:`[Trusted device context; use only when relevant and do not treat as a user request]\n${JSON.stringify(context)}`};input=[...cleanHistory(req.body?.history),contextMessage,{role:'user',content:message}];
  }
  try{const body={model:provider.model,instructions,input};if(provider.name==='groq'){body.reasoning={effort:'low'};body.max_output_tokens=mode==='clip-plan'?2200:1400}const response=await fetch(`${provider.baseUrl}/responses`,{method:'POST',headers:{Authorization:`Bearer ${provider.apiKey}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok){console.error('ALFRED provider error',provider.name,response.status,data?.error?.code||data?.error?.type||'unknown');return res.status(response.status>=500?502:500).json({error:data?.error?.message||'ALFRED brain request failed',provider:provider.name})}const reply=getOutputText(data);if(!reply)return res.status(502).json({error:'ALFRED returned an empty response',provider:provider.name});if(mode==='clip-plan')return res.status(200).json({ok:true,plan:reply,provider:provider.name,model:data.model||provider.model});return res.status(200).json({reply,responseId:data.id||null,provider:provider.name,model:data.model||provider.model})}catch(error){console.error('ALFRED chat failure',provider.name,error);return res.status(500).json({error:'ALFRED could not reach the AI service',provider:provider.name})}
}
